export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE = 'POPUP_CLOSE';

export const GET_ADS_LIST_REQUEST = 'GET_ADS_LIST_REQUEST';
export const GET_ADS_LIST_SUCCESS = 'GET_ADS_LIST_SUCCESS';
export const GET_ADS_LIST_FAILURE = 'GET_ADS_LIST_FAILURE';
