export const POPUP_OPEN = 'POPUP_OPEN';
export const POPUP_CLOSE = 'POPUP_CLOSE';

export const GET_ADS_LIST_REQUEST = 'GET_ADS_LIST_REQUEST';
export const GET_ADS_LIST_SUCCESS = 'GET_ADS_LIST_SUCCESS';
export const GET_ADS_LIST_FAILURE = 'GET_ADS_LIST_FAILURE';

export const NEW_ADS_REQUEST = 'NEW_ADS_REQUEST';
export const NEW_ADS_SUCCESS = 'NEW_ADS_SUCCESS';
export const NEW_ADS_FAILURE = 'NEW_ADS_FAILURE';
